---
version: "2.0"

services:
  auth-api:
    # Use Node base image (no Docker build required)
    image: node:20-alpine
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
    env:
      # Core Configuration
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=/app/data/auth.db

      # JWT Secrets - THESE ARE TEST SECRETS FOR SANDBOX ONLY!
      - JWT_SECRET=sandbox-test-secret-change-for-production
      - JWT_REFRESH_SECRET=sandbox-test-refresh-secret-change-for-production
      - JWT_EXPIRES_IN=15m
      - JWT_REFRESH_EXPIRES_IN=7d

      # URLs - Will be updated after deployment
      - DOMAIN=sandbox.akash.network
      - APP_URL=http://sandbox-deployment
      - FRONTEND_URL=http://localhost:5173
      - CORS_ORIGIN=*

      # Email Service (optional for sandbox testing)
      - RESEND_API_KEY=test_key

      # SMS Service (optional for sandbox testing)
      - HTTPSMS_API_KEY=test_key
      - HTTPSMS_PHONE_NUMBER=+1234567890

      # OAuth credentials - Add your real ones to test OAuth
      - GOOGLE_CLIENT_ID=your_google_client_id
      - GOOGLE_CLIENT_SECRET=your_google_secret
      - GOOGLE_REDIRECT_URI=http://your-sandbox-url/auth/oauth/callback/google

      - GITHUB_CLIENT_ID=your_github_client_id
      - GITHUB_CLIENT_SECRET=your_github_secret
      - GITHUB_REDIRECT_URI=http://your-sandbox-url/auth/oauth/callback/github

      - TWITTER_CLIENT_ID=your_twitter_client_id
      - TWITTER_CLIENT_SECRET=your_twitter_secret
      - TWITTER_REDIRECT_URI=http://your-sandbox-url/auth/oauth/callback/twitter

      - DISCORD_CLIENT_ID=your_discord_client_id
      - DISCORD_CLIENT_SECRET=your_discord_secret
      - DISCORD_REDIRECT_URI=http://your-sandbox-url/auth/oauth/callback/discord

    # Build and run from GitHub
    command:
      - sh
      - -c
    args:
      - >-
        apk add --no-cache git &&
        git clone https://github.com/alternatefutures/alternatefutures-auth.git /app &&
        cd /app &&
        git checkout feat/alt-32-auth-system &&
        npm install &&
        npm run build &&
        node dist/index.js

profiles:
  compute:
    auth-api:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 1Gi
        storage:
          size: 2Gi

  placement:
    akash:
      pricing:
        auth-api:
          denom: uakt
          amount: 1000

deployment:
  auth-api:
    akash:
      profile: auth-api
      count: 1
