---
# Akash SDL Template - DO NOT commit actual secrets here
# Use deploy script or GitHub Actions to inject secrets at deploy time
#
# MIGRATION NOTE: This service now uses PostgreSQL instead of SQLite.
# Database connection is via the shared PostgreSQL deployment (service-cloud-api's postgres).
# The DATABASE_URL is fetched from Infisical at runtime.
version: "2.0"

services:
  auth-api:
    image: ghcr.io/alternatefutures/auth-service:latest
    credentials:
      host: ghcr.io
      username: alternatefutures
      password: ${GHCR_PAT}  # Injected at deploy time
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
        accept:
          - auth.alternatefutures.ai
    env:
      # Core Configuration
      - NODE_ENV=production
      - PORT=3000
      # DATABASE_URL is now fetched from Infisical at runtime (PostgreSQL connection string)
      # Format: postgresql://user:password@host:5432/database

      # JWT Token Expiry (non-sensitive)
      - JWT_EXPIRES_IN=15m
      - JWT_REFRESH_EXPIRES_IN=7d

      # URLs (non-sensitive)
      - DOMAIN=alternatefutures.ai
      - APP_URL=https://auth.alternatefutures.ai
      - FRONTEND_URL=https://app.alternatefutures.ai
      - CORS_ORIGIN=https://app.alternatefutures.ai

      # OAuth Redirect URIs (non-sensitive, just URLs)
      - GOOGLE_REDIRECT_URI=https://auth.alternatefutures.ai/auth/oauth/callback/google
      - GITHUB_REDIRECT_URI=https://auth.alternatefutures.ai/auth/oauth/callback/github
      - TWITTER_REDIRECT_URI=https://auth.alternatefutures.ai/auth/oauth/callback/twitter
      - DISCORD_REDIRECT_URI=https://auth.alternatefutures.ai/auth/oauth/callback/discord

      # Infisical credentials - injected at deploy time from GitHub Secrets
      - INFISICAL_SITE_URL=https://secrets.alternatefutures.ai
      - INFISICAL_CLIENT_ID=${INFISICAL_CLIENT_ID}
      - INFISICAL_CLIENT_SECRET=${INFISICAL_CLIENT_SECRET}
      - INFISICAL_PROJECT_ID=${INFISICAL_PROJECT_ID}
      - INFISICAL_ENVIRONMENT=prod

profiles:
  compute:
    auth-api:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 1Gi
        storage:
          - size: 1Gi

  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        auth-api:
          denom: uakt
          amount: 100

deployment:
  auth-api:
    akash:
      profile: auth-api
      count: 1
